### ISSUE TITLE
Local volume usage is documented wrong, and omits info about how to access the full contents of each telegram.

### ISSUE THREAD

**Issue by f-steff** [moonbuggy/docker-syslog-ng-alpine#1]
I've just managed to set up the image to properly receive RFC 5424 formatted messages.
I noticed a few issues with the documentation.

The documentation currently states:
> If you're using the local destination you could mount /var/log/messages as a volume (e.g. add -v syslog-ng_messages:/var/log/messages to the run command).

Based on the above I wrote the following on windows which didn't work: -v /c/docker/syslog-ng_messages:/var/log/messages
In this way, a folder names messages will be created, which remains empty.

Instead, this method worked: -v /c/docker/syslog-ng_messages:/var/log/

Doing it this way also exposed that two log-files are created:

- messages
- messages-kv.log

The **messages** files contain the message part of each telegram send but do not have any of the RFC 5424 specific parts.
The **messages-kv.log** file, on the other hand, contains the complete message, including structured_data.

For me, access to the latter file is vital. :-)

Thank you for sharing your work!

**Comment by moonbuggy** [comment]
Excellent, thanks for letting me know there's an issue. I'm logging to SQL here, so I maybe haven't tested the local destination as well as I should have. :)

I expect to be pushing a whole build system and enabling multi-arch images on this repo in the next few days. As well as improving the implementation of the config-via-ENV stuff now I know how to work things better. I'll fix my dodgy documentation at the same time. :)

**Comment by moonbuggy** [comment]
This issue should be resolved by 9ee1369422625ebb723a4f4dbe4d11f99adb81a0.

Multi-arch and a healthcheck as well. Good times. :) Although I didn't come up with a more satisfactory way to handle the aspects of the config-via-ENV that I dislike.

Anyway, before I close the issue, do you have any further thoughts? Is the change adequate from your perspective?

**Comment by f-steff** [comment]
Thank you for your quick response. Your changes look great and I'm looking forward to upgrading, but can't interrupt my running system at the moment. 
I do not have further thoughts related to the specific issue, and you are welcome to close it.

**Comment by moonbuggy** [comment]
Cool. Thanks for the feedback. :)
